name: Frontend CI

on: [push]

env:
  BUCKET_NAME: "llevox-frontend-ws"
  DISTRIBUTION_ID: "E1SJL8M3WJFEX3"
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: echo "npm install"
      - name: Run developer tests
        run: echo "run test"

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: echo "npm ci"

      - name: Build frontend
        run: echo "npm run build"


  deploy:
    needs: [test, build]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy to S3 Bucket
        run: |
          aws s3 sync ./ s3://$BUCKET_NAME

      - name: Invalidate Cloudfront CDN
        run: aws cloudfront create-invalidation --distribution-id=$DISTRIBUTION_ID --paths '/*'
